version: "3"

services:
    nginx:
        image: nginx:latest
        ports:
            - "8076:80"
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db

    db:
        image: mysql:8.4
        restart: always
        environment:
            MYSQL_DATABASE: url_shortener
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./tmp/db:/var/lib/mysql
        ports:
            - "8101:3306"
